{{/* EKS-specific security-bundle Helm values*/}}
{{- define "EKSSecurityBundleHelmValues" }}
userConfig:
  kyverno:
    configMap:
      values:
        kyverno:
          admissionController:
            tolerations:
            - key: "node.cluster.x-k8s.io/uninitialized"
              operator: "Exists"
              effect: "NoSchedule"
{{- end }}
