{{- define "defaultAwsEbsCsiDriverHelmValues" -}}
clusterID: {{ include "resource.default.name" . }}
clusterName: {{ include "resource.default.name" . }}
helmRelease:
  dependsOn:
  - cilium
  {{- if .Values.cluster.providerIntegration.apps.securityBundle.enable }}
  - kyverno-crds
  {{- end }}
  {{- if .Values.cluster.providerIntegration.apps.verticalPodAutoscalerCrd.enable }}
  - vertical-pod-autoscaler-crd
  {{- end }}
extraVolumeTags: {{ include "resource.default.additionalTags" . | nindent 2 }}
{{- if (.Values.global.connectivity.proxy).enabled }}
proxy:
  http: {{ .Values.global.connectivity.proxy.httpProxy | quote }}
  https: {{ .Values.global.connectivity.proxy.httpsProxy | quote }}
  noProxy: {{ include "cluster.connectivity.proxy.noProxy" (dict "global" .Values.global "providerIntegration" .Values.cluster.providerIntegration) | quote }}
{{- end }}
global:
  image:
    registry: {{ include "awsContainerImageRegistry" . }}
  podSecurityStandards:
    {{- /* PolicyException CRD only available with security-bundle installed */}}
    enforced: {{ and .Values.global.podSecurityStandards.enforced .Values.cluster.providerIntegration.apps.securityBundle.enable }}
{{- if not .Values.cluster.providerIntegration.apps.verticalPodAutoscalerCrd.enable }}
verticalPodAutoscaler:
  enabled: false
{{- end }}
{{- if not .Values.cluster.providerIntegration.apps.observabilityBundle.enable }}
upstream:
  controller:
    enableMetrics: false
    serviceMonitor:
      forceEnable: false
{{- end }}
{{- end }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: {{ include "resource.default.name" . }}-aws-ebs-csi-driver-bundle
  namespace: {{ .Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: {{ .Values.global.metadata.description | quote }}
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    {{- include "labels.common" . | nindent 4 }}
spec:
  {{- $_ := set $ "appName" "aws-ebs-csi-driver" }}
  url: oci://gsoci.azurecr.io/charts/giantswarm/aws-ebs-csi-driver-bundle
  ref:
    tag: {{ include "cluster.app.version" . }}
  interval: 24h
  timeout: 60s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" . }}-aws-ebs-csi-driver-bundle
  namespace: {{ .Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: {{ .Values.global.metadata.description | quote }}
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    {{- include "labels.common" . | nindent 4 }}
spec:
  releaseName: {{ include "resource.default.name" . }}-aws-ebs-csi-driver-bundle
  targetNamespace: {{ .Release.Namespace | quote }}
  storageNamespace: {{ .Release.Namespace | quote }}
  chartRef:
    kind: OCIRepository
    name: {{ include "resource.default.name" . }}-aws-ebs-csi-driver-bundle
  serviceAccountName: automation
  interval: 5m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  {{- $awsEbsCsiDriverHelmValues := include "defaultAwsEbsCsiDriverHelmValues" . | fromYaml }}
  {{- $customAwsEbsCsiDriverHelmValues := (((.Values.global).apps).awsEbsCsiDriver).values }}
  {{- if $customAwsEbsCsiDriverHelmValues }}
  {{- $awsEbsCsiDriverHelmValues = merge (deepCopy $customAwsEbsCsiDriverHelmValues) $awsEbsCsiDriverHelmValues }}
  {{- end }}
  {{- if $awsEbsCsiDriverHelmValues }}
  values:
    {{- $awsEbsCsiDriverHelmValues | toYaml | nindent 4 }}
  {{- end }}
  {{- if (((.Values.global).apps).awsEbsCsiDriver).extraConfigs }}
  valuesFrom:
  {{- range $config := (((.Values.global).apps).awsEbsCsiDriver).extraConfigs }}
  - kind: {{ $config.kind }}
    name: {{ $config.name }}
    valuesKey: values
    optional: {{ $config.optional | default false }}
  {{- end }}
  {{- end }}
