apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-cilium
  namespace: {{ $.Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.global.metadata.description }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  releaseName: cilium
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: cilium
      # used by renovate
      # repo: giantswarm/cilium-app
      version: 0.24.0
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-default
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  dependsOn:
    - name: {{ include "resource.default.name" $ }}-vertical-pod-autoscaler-crd
      namespace: {{ $.Release.Namespace }}
  interval: 4m
  install:
    remediation:
      retries: 200
  valuesFrom:
  - kind: ConfigMap
    name: {{ include "resource.default.name" $ }}-control-plane-endpoint
    valuesKey: control_plane_endpoint_host
    targetPath: "k8sServiceHost"
  # Default values
  # https://github.com/giantswarm/cilium-app/blob/main/helm/cilium/values.yaml
  values:
    global:
      podSecurityStandards:
        enforced: {{ .Values.global.podSecurityStandards.enforced }}
    eni:
      enabled: true
    ipam:
      mode: eni
    operator:
      extraArgs:
        - "--aws-release-excess-ips=true"
    enableIPv4Masquerade: false
    tunnel: disabled
    cluster:
      name: {{ include "resource.default.name" $ }}
    cni:
      customConf: true
      exclusive: true
      configMap: cilium-cni-configuration
    cniCustomConf:
      eni:
        firstInterfaceIndex: 1
        securityGroupTags:
          "kubernetes.io/cluster/{{ include "resource.default.name" $ }}": "owned"
          "aws:eks:cluster-name": "{{ include "resource.default.name" $ }}"
        subnetTags:
          "sigs.k8s.io/cluster-api-provider-aws/cluster/{{ include "resource.default.name" $ }}": "owned"
          "sigs.k8s.io/cluster-api-provider-aws/association": "secondary"
          "sigs.k8s.io/cluster-api-provider-aws/role": "private"
    k8sServicePort: '443'
    kubeProxyReplacement: 'true'
    hubble:
      relay:
        enabled: true
