apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-cilium
  namespace: {{ $.Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.global.metadata.description }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  releaseName: cilium
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: cilium
      # used by renovate
      # repo: giantswarm/cilium-app
      version: 0.27.0-b2e95ed09cba87665cb3a44a588a36dc5a4b6d65
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-default-test
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  dependsOn:
    - name: {{ include "resource.default.name" $ }}-vertical-pod-autoscaler-crd
      namespace: {{ $.Release.Namespace }}
  interval: 4m
  install:
    remediation:
      retries: 200
  valuesFrom:
  - kind: ConfigMap
    name: {{ include "resource.default.name" $ }}-control-plane-endpoint
    valuesKey: control_plane_endpoint_host
    targetPath: "k8sServiceHost"
  # Default values
  # https://github.com/giantswarm/cilium-app/blob/main/helm/cilium/values.yaml
  values:
    global:
      podSecurityStandards:
        enforced: {{ .Values.global.podSecurityStandards.enforced }}
    eni:
      enabled: true
    ipam:
      mode: eni
    eksMode: true
    operator:
      extraArgs:
        - "--aws-release-excess-ips=true"
    enableIPv4Masquerade: false
    tunnel: disabled
    cluster:
      name: {{ include "resource.default.name" $ }}
    cni:
      customConf: true
      exclusive: true
      configMap: cilium-cni-configuration
    k8sServicePort: '443'
    kubeProxyReplacement: strict
    hubble:
      relay:
        enabled: true
