apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-cilium
  namespace: {{ $.Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.metadata.description }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  releaseName: cilium
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: cilium
      # used by renovate
      # repo: giantswarm/cilium-app
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-default
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  dependsOn:
    - name: {{ include "resource.default.name" $ }}-vertical-pod-autoscaler-crd
      namespace: {{ $.Release.Namespace }}
  interval: 10m
  install:
    remediation:
      retries: 200
  valuesFrom:
  - kind: ConfigMap
    name: {{ include "resource.default.name" $ }}-control-plane-endpoint
    valuesKey: control_plane_endpoint_host
    targetPath: "k8sServiceHost"
  # Default values
  # https://github.com/giantswarm/cilium-app/blob/main/helm/cilium/values.yaml
  values:
    ipam:
      mode: cluster-pool-v2beta
      operator:
        clusterPoolIPv4PodCIDRList:
          {{- range $value := .Values.connectivity.network.pods.cidrBlocks }}
          - {{ $value }}
          {{- end }}
    k8sServicePort: '443'
    kubeProxyReplacement: strict
    hubble:
      relay:
        enabled: true
    defaultPolicies:
      enabled: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
