{{- include "validation" . }}
---
{{- if semverCompare "<1.25.0" .Values.internal.kubernetesVersion -}}
{{- include "psps" . }}
---
{{- end }}
{{- include "coredns" . }}
---
{{- include "cluster" . }}
---
{{- include "aws-cluster" . }}
---
{{- include "control-plane" . }}
---
{{- include "machine-pools" . }}
